### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by mozi-h** [wintergatan-community/virtual-mmx#8]
[Figma UI mockup](https://www.figma.com/file/VgAtp5bYQr0g6s2MOB2QwV/Virtual-MMX)
@iansedano

**Comment by xxfast** [comment]
Interested in this

**Comment by Butch13-Gaming** [comment]
Throwing in another layout design that is more MMX first DAW second as opposed to DAW first MMX second:
https://drive.google.com/file/d/1LzLM6b2tGgYS2zl5Le-WCRd46IveVi7I/view?usp=sharing
Sorry for the garbage quality, but I only had a few minutes to make this today.

**Comment by ollpu** [comment]
Some rough sketching in the spirit of @butch81385's layout:
https://drive.google.com/file/d/1nhWKWvpk774TqvGzlPAzZoZI_qfFChN5/view?usp=sharing

I tried to include all the bells and whistles on the MMX off the top of my head, all of which obviously aren't necessary to implement initially. Making this responsive would be a challenge to say the least.

**Edit:** A further sketch of my vision of the programming wheel. (custom designed gear texture)
![concept](https://user-images.githubusercontent.com/7241014/83362895-98fafd00-a39d-11ea-89e4-e44ac6a70f6f.png)

**Comment by mozi-h** [comment]
> From [Locket Rauncher#9748](https://discordapp.com/channels/649165975647682560/712733531687878676/714746074975174766) in Discord

Users should be able to turn individual channels on and off in the UI through some global toggle.

That way, if you only want to work on the drums, then you don't have the entire programming wheel present on screen.

**Comment by ollpu** [comment]
A digitized version of my mock-up (as per @Zakgriffin's request).
![image](https://user-images.githubusercontent.com/7241014/84441841-29122f80-ac45-11ea-8d9d-4a51368ed76e.png)

[The gimp file](https://drive.google.com/file/d/1rivKN-luo4KNDZLkevr68RTu25TKb7je/view?usp=sharing) if you want to have a look at it.

Thoughts that came up while making this:
- I hate gimp.
  - No, I just don't know how to use it and this isn't the best tool for the job either.
- Resizing. It's not too hard for the instruments on the bottom to get out of the way (or decay into just text) if you want to work with a larger programming area. (same with sideways resize I suppose) Hence, the resize-corner.
  - It's a little awkward to have vibraphone note names both on the top and on the bottom, almost aligned but not quite. They are aligned now, but if you scroll to the right on the wheel, they won't be.
    - -> an alternative idea is to not show channel names on top, but have respective clickable icons on the top, scrolling with the rest of the wheel.
- Vibraphone plates & the drum kit. Not a big fan of the look currently. Improvement ideas are welcome.
  - Yes or no: different size vibraphone plates depending on the pitch? Currently, it's the only thing that really makes it look like a vibraphone so it makes sense. To really match the MMX look they should also be vertically staggered ;)
- Bass.
  - I tried modelling the bass head stock (paths might still exist in the gimp file) but it felt too bulky to really work. I think it looks close enough to a bass without it as well. Tuning can still be chosen by clicking up there.
  - Frets are unnaturally spaced but UI-wise it works better. Any bassists have objections to this?
- Beat division selector. There was some discussion about this on Discord. My current solution in the mock-up is to show the default ("native") options as buttons (eighth - triplet - sixteenth), a non-quantized option (the opened padlock icon ..or something else?), and a dropdown on the right for further divisions.
- The "random levers". When I made the sketch, I didn't think about these too much. I believe they are currently laid out on the machine as follows:
  1. Cymbal hit & damp. (push-pull, eek)
  [hi-hat machine in between]
  1. Vibraphone damping
  1. HI-hat tension control
  1. Brake
  They are similar, but maybe not similar enough. Would it make sense to just put these controls around their respective instruments? The cymbal is a weird case especially. For other instruments we support manual triggering via dropping a marble, so technically there are two ways to trigger the cymbal. Does it make sense to also be able to trigger it from two places in the UI?
- The gray box on the right is for transport controls and other stuff.
  - Is there enough other stuff to justify it being that large? Of course there'll be a lot of recording related things, but they might not be situated here.
  - I didn't finish it, partially because I ran out of motivation and partially because I don't want to make the same CSS button a third time. I have a history of designing buttons like this:
![image](https://user-images.githubusercontent.com/7241014/84443645-b2773100-ac48-11ea-84c1-8938b254053e.png) ![image](https://user-images.githubusercontent.com/7241014/84443704-d175c300-ac48-11ea-85b5-cc1e7c243413.png)

Please do voice your comments and ideas!

**Comment by iansedano** [comment]
Nice work @ollpu ! 
I'll throw some ideas out in response to your post.

Re vibraphone resizing and scrolling. Maybe coloring the respective area on the vibraphone is enough, something like this:
![image](https://user-images.githubusercontent.com/38072365/84472205-233d3e00-ac87-11ea-8b40-cbb299605173.png)

Re: Drumkit. Maybe finding a decent image of the drums and masking them. I have started on one here, just spend a few minutes on it, but if I spend some more time on it I could make it look much cleaner. I could potentially even try and "cartoonify" or stylize it a bit.
![image](https://user-images.githubusercontent.com/38072365/84473194-e7a37380-ac88-11ea-8fcf-166868506503.png)

Though I don't mind your drums, nice and simple.

Vibraphone plates, I like the way they look. I don't think that for this "version" we should be too worried about staggering them and getting the "rubber pads" for example. It does make sense to have a separate image file for each note with its corresponding size, that doesn't sound too difficult? (I could generate those if we decide we want it) Yet at the same time, static size is not very distracting.

Bass looks great, I wouldn't try and get fret spacing to be realistic, as you say, for UI it will work much better this way. Also agree that head-stock may be nice but it would take up a lot of screen space which we are short of. 

Re: Rhythm selector - also looks great to me. The buttons also great. I'm not sure what you mean by the un-quantized version. Also unsure of the further beat divisions as the rhythm machine is limited to the off-beat, 16th and triplets, any more subdivisions would be MMX "virtually extended" territory.

Re: Levers - I like the way they are grouped as if on the marble machine. With some labeling or some icons I think it would be fine. Having the option to trigger it elsewhere is also a nice quality of life thing to have.

Re: Transport - Its nice to have a big play button :) so I wouldn't worry about it being large. Though it might be an idea to discuss what we will have there. I'll just throw out a list here to get that conversation started.

* Play
* Pause
* Stop (Reset)
* Performance Record?
* Clock (it would display what "tick" we are on and what position on the programming wheel etc.

Can't think of any more just now.

**Comment by ollpu** [comment]
@iansedano, great to have some feedback!

- Vibraphone resizing and scrolling. Not quite sure what problem you're addressing with this, but maybe some tint on the background makes sense. The awkwardness I tried to explain is with having the note names (C - D - E♭...) visible both on the top as guides for the programming wheel, and on the bottom as clickable instruments. Especially if the programming area is made larger and the instruments decay into text, then the same markings will be on the top and on the bottom. But if the instruments are stationary, they won't be aligned with the programming wheel (which can scroll to the right).
- Vibraphone. Unless we have some physical textures, we probably want them to be SVGs or just HTML boxes anyways. The way they're currently drawn makes them super simple to do with CSS box-shadow. So implementation of different heights shouldn't be an issue.
- Rhythm selector. Note that with "beat division selector" I'm referencing the panel on the bottom of the programming area, not the hi-hat machine which of course has limited capabilities. As for the beat division selector, I think it's nice to be able to work in divisions other than the ones on the black plates. It's also possible with the machine with stud welded plates. Un-quantized mode is the "freehand mode", where there's no snapping to grid. Maybe it doesn't make sense while manipulating notes with the mouse, but very desirable when playing "live" with a keyboard or MIDI input. (or maybe settings for that go in a different place)

**Comment by mozi-h** [comment]
Neat mock up; I like it!

With the vibraphone displaying notes twice I wouldn't be too worried:
- You might want to play different instruments quickly after another manually, without having to scroll like a madman on the editing plane.
- In the future, the notes on top of the editing view could be used to swap the note / bass string, instead of manually playing.

---

> [...] instruments decay into text [...]

You're referring to responsiveness on smaller screens, right?
I don't really understand; why would you decay a visual representation into plain text? An appropriate visual alternative (changing layout to be vertical-friendly, changing spacing, etc.) would be way better and just as much to do as converting it to `Vibraphone: C4 D4 E4 F4 G4 A4 B4 C5 D5 E5 F5`?

**Comment by FelixWohlfrom** [comment]
Also love the mockup and even more with the recommendation of @iansedano to use different colors for vibraphone and other instruments (maybe even different colors for drumkit and bass?)

I personally would prefer the "simple" style of the drumkit, it feels like it fits more to the rest of the mockup.

Regarding the buttons: I also would love a big play button. 
Maybe we should also add there a "save", "load" and "new" button?

**Comment by ollpu** [comment]
@mozi-h Not necessarily on smaller screens, I'm also thinking of allowing the programming wheel to be resized by the user (like a textarea). I guess you're right, it makes more sense to have a more compact design instead of text.

**Comment by ollpu** [comment]
@iansedano, @FelixWohlfrom: A simpler version works better, yes, but I think my current version is a bit too simple and flat. Adding a tad more details might make it better.

**Comment by iansedano** [comment]
@ollpu i'll properly mask the one i cut out from the mmx and "svg" it just to see the results, don't have to use it but will post once I have it done.

**Comment by FelixWohlfrom** [comment]
> @ollpu i'll properly mask the one i cut out from the mmx and "svg" it just to see the results, don't have to use it but will post once I have it done.

What about a mixed version? Still schematic, but instead of the current top down view a little sideways view to get a little 3d impression? Unfortunately my graphics talents are quite limited, but I hope you get the idea...

**Comment by iansedano** [comment]
Yes, i'm going to try and trace it, so it still has some of the finer details of the drums but still schematic-like to fit in with the general vibe we are going for here

**Comment by iansedano** [comment]
Below are some attempts at simplifying the image...and I am none too happy with them. I hoped to be able to trace them and give them a "schematic" look. I have spent hours looking for decent schematic drawings of drum components and not finding anthing really suitable (maybe the snare drum one on the right can be adapted, but perhaps that is too "cartoony").

Cymbals are very hard to represent as a schematic without losing that "cymbal" look!

I'm thinking that @ollpu one is more fitting! We could always use his as a placeholder if we are not too happy at the moment. The MMX CAD team should be able to produce a very convincing one from any angle once they are done (though not sure when that might be).

The last image is from the MMX poster, but this is also not really on the same level of detail!

<img src="https://user-images.githubusercontent.com/38072365/87557890-c1725880-c6b8-11ea-9b95-4853d2315b03.png" width="200"> <img src="https://user-images.githubusercontent.com/38072365/87557897-c2a38580-c6b8-11ea-996e-043cf0f32847.png" width="200"> <img src="https://user-images.githubusercontent.com/38072365/87558335-48273580-c6b9-11ea-928e-6a4dde723a29.gif" width="200"> <img src="https://user-images.githubusercontent.com/38072365/87559155-385c2100-c6ba-11ea-98fb-1f1606658b19.png" width="200">

**Comment by AntonyGarand** [comment]
I think this is considered done, as the [current website](https://wintergatan-community.github.io/virtual-mmx/) matches this UI?  
If so, I'll close the issue!

**Comment by ollpu** [comment]
Yep, I think the mock-ups here are more or less done, though not fully implemented yet. Further design and finer details can live elsewhere when they are worked on.
